export default {
	EVENT_TYPE_PLAIN: 0,
	EVENT_TYPE_HOMEWORK: 1,
	EVENT_TYPE_SCHEDULE: 2,

	EVENT_TAG_RESERVED: 0,
	EVENT_TAG_DESCRIPTION: 1,
	EVENT_TAG_HOMEWORK: 2,
	EVENT_TAG_TERM_ID: 3,
	EVENT_TAG_CLASS_ID: 4,
	EVENT_TAG_OWNER_ID: 5,
	EVENT_TAG_OWNER_NAME: 6,
	EVENT_TAG_DAY_NUMBER: 7,
	EVENT_TAG_BLOCK: 8,
	EVENT_TAG_BUILDING_NAME: 9,
	EVENT_TAG_ROOM_NUMBER: 10
};